force-app/main/default/objects/Dealership__c/Dealership__c.object-meta.xml
<CustomObject>
    <description>Specific Dealership</description>
    <label>Dealership</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealership__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealership__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dealership__c.field-meta.xml
<CustomField>
    <fullName>Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealership</label>
    <referenceTo>Dealership__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DealershipController.cls
public with sharing class DealershipController {
    
    public List<Opportunity> currentDealerOpportunities {get;set;}
    
    public String currentDealerName {get;set;}
    
    public List<Dealership__c> dealerships {get;set;}
    
    public List<Wrap> wrappedDealers {get;set;}
    
    
    public DealershipController() {
        
        try {
			dealerships = [SELECT Name, City__c, State__c FROM Dealership__c];
        } 
        catch (Exception e) {
            system.debug(e);
        }
        
        wrappedDealers = new List<Wrap>();
        for(Dealership__c d : dealerships) {
            wrappedDealers.add(new Wrap(d));
        }
	}
    
    
    
    
	public  void changeDealer() {
    	currentDealerOpportunities = [SELECT Name, Amount, CloseDate,StageName  FROM Opportunity WHERE (Opportunity.Dealership__r.Name = :currentDealerName AND StageName != 'Closed')];
	}
    
    
    
    
    
    
    
    private class Wrap {
        public Dealership__c wrappedDealer {get; set;}
        public Opportunity topOpp {get;set;}
            
         public Wrap(Dealership__c d) {
           wrappedDealer = d;
             try{
                topOpp = [SELECT Name, Amount FROM Opportunity WHERE (Opportunity.Dealership__r.ID = :d.Id AND StageName != 'Closed' )
                      ORDER BY Amount DESC LIMIT 1][0];
             } 
             catch(Exception e) {
                 system.debug(e);
             }
            
          }
    }
}